name: Pipeline Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install asdf required dependencies
        run: sudo apt-get install -y curl git
      - name: install asdf
        run: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ls -l
      
