name: Deployment Pipeline 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: runtime version manager
        uses: asdf-vm/actions/install@v2
      - name: install dependencies
        run: yarn install
      - name: code linting
        run: yarn lint
      - name: build
        run: yarn start
      - name: test
        run: yarn test