name: Deployment Pipeline 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: check vulnerabilities with sync
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v2
      - name: install dependencies
        run: yarn install
      - name: code linting
        run: yarn lint

  test:
    runs-on: ubuntu-20.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v2
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test

  deploy:
    if: github.event_name == 'push'
    needs: [lint, test, security]
    runs-on: ubuntu-20.04
    steps:
      - name: deploy to Render
        run: curl ${{ secrets.RENDER_HOOK }}