name: Deployment Pipeline 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v2
      - name: install dependencies
        run: yarn install
      - name: code linting
        run: yarn lint

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v2
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test

  deploy:
    if: github.event_name == 'push'
    needs: [lint, test]
    runs-on: ubuntu-20.04
    steps:
      - name: deploy to Render
        run: curl ${{secrets.RENDER_HOOK}}